In [6]:
import random
random.randint(1,5)

2

In [39]:
import numpy as np
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 62,  55,  55,  54,  88],
       [ 59,  84,  57,  62,  75],
       [ 66,  80,  98,  61,  80],
       [ 58,  67,  90,  79,  51],
       [ 74,  64,  81,  68,  51],
       [ 71,  90,  77,  85,  58],
       [ 63,  55,  64,  54,  83],
       [ 82,  87,  92,  87,  69],
       [ 59,  62,  95,  81,  74],
       [ 83,  53,  67,  80,  86],
       [ 86,  71,  89,  70,  59],
       [ 82,  92,  55,  82,  53],
       [ 58,  82,  90,  76,  66],
       [ 94,  69,  75,  67,  82],
       [ 89,  61,  86,  86,  50],
       [ 83,  75,  97, 100,  99],
       [ 96,  56,  75,  58,  91],
       [ 72,  82,  69,  77,  81],
       [100,  74,  84,  64,  90],
       [ 50,  54,  77,  62,  97],
       [ 59,  67,  68,  98,  92],
       [ 96,  68,  76,  57,  79],
       [ 76,  78,  77,  51,  99],
       [ 67,  63,  92,  53,  55],
       [ 85,  72,  98,  95, 100],
       [ 72,  99,  50,  56,  82],
       [ 85,  63,  65,  85,  93],
       [ 58,  53,  96,  55,  72],
       [ 97,  52,  80,  69,  82],
       [ 62,  

In [37]:
scores[0]

array([ 92,  78,  95, 100,  64])

In [40]:
scores[0:3]

array([[62, 55, 55, 54, 88],
       [59, 84, 57, 62, 75],
       [66, 80, 98, 61, 80]])

In [41]:
scores[0:3,0]

array([62, 59, 66])